name: create-pr

on: workflow_dispatch

permissions: write-all


jobs:
  createpr:
    name: createpr
    runs-on: ubuntu-latest
    env:
      working-directory: ${{ github.workspace }}/changes
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: makechange
        id: makechange
        shell: pwsh
        run: |
          # Git setup
          echo "Run ID: ${{ github.run_id }}"
          git config user.email "rollback-changes@thing.com"
          git config user.name "rollback-changes"
          git checkout main
          git pull
          git checkout -b testpr/${{ github.run_id }}
          # make white space change
          if (test-path testing.txt) {
            echo " " >> testing.txt
          }
          else {
            echo " " > testing.txt
          }
          git add testing.txt
          git commit -m "Test PR"
          git push origin HEAD

      - name: raisepr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl \
          -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls \
          -d '{
            "title": "Test PR",
            "body": "Test PR",
            "head": "testpr/${{ github.run_id }}",
            "base": "main"
          }')
          
          echo "PR_URL=$(echo $response | jq -r '.html_url')" >> $GITHUB_ENV

      - name: addprcomment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "PR URL: ${{ env.PR_URL }}"
          echo $PR_URL
          response=$(curl \
          -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          ${{ env.PR_URL }}/comments \
          -d '{
            "body": "Test PR"
          }')
          echo "PR_COMMENT_URL=$(echo $response | jq -r '.html_url')" >> $GITHUB_ENV